In [1]:
%load_ext nb_black

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import plotly.express as px
from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt
from PIL import Image

In [14]:
df_county = pd.read_csv("Data/SVI2018_US_COUNTY.csv")
df_census = pd.read_csv("Data/SVI2018_US.csv")
display(df_county)
display(df_census)

,ST,STATE,ST_ABBR,COUNTY,FIPS,LOCATION,AREA_SQMI,E_TOTPOP,M_TOTPOP,E_HU,...,F_CROWD,F_NOVEH,F_GROUPQ,F_THEME4,F_TOTAL,E_UNINSUR,M_UNINSUR,EP_UNINSUR,MP_UNINSUR,E_DAYPOP
0,35,NEW MEXICO,NM,Rio Arriba,35039,"Rio Arriba County, New Mexico",5860.869195,39307,0,20044,...,0,0,0,1,-999,4160,588,10.6,1.5,32290
1,1,ALABAMA,AL,Autauga,1001,"Autauga County, Alabama",594.443459,55200,0,23315,...,0,0,0,0,0,3875,508,7.1,0.9,37301
2,1,ALABAMA,AL,Blount,1009,"Blount County, Alabama",644.830460,57645,0,24222,...,0,0,0,0,0,6303,732,11.0,1.3,40036
3,1,ALABAMA,AL,Butler,1013,"Butler County, Alabama",776.838201,20025,0,10026,...,0,0,0,0,0,2005,340,10.2,1.7,17280
4,1,ALABAMA,AL,Calhoun,1015,"Calhoun County, Alabama",605.867251,115098,0,53682,...,0,0,0,0,0,10686,796,9.4,0.7,117894
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3137,48,TEXAS,TX,Duval,48131,"Duval County, Texas",1793.476183,11355,0,5592,...,1,1,0,2,10,2656,406,24.5,3.7,9592
3138,48,TEXAS,TX,Zapata,48505,"Zapata County, Texas",998.411980,14369,0,6388,...,1,0,0,2,10,4206,484,29.3,3.4,10924
3139,48,TEXAS,TX,Zavala,48507,"Zavala County, Texas",1297.406535,12131,0,4344,...,1,1,0,2,10,2194,354,18.4,3.0,10672
3140,48,TEXAS,TX,Dimmit,48127,"Dimmit County, Texas",1328.884075,10663,0,4408,...,1,1,0,2,11,2345,539,22.2,5.1,8229
3141,48,TEXAS,TX,Jim Hogg,48247,"Jim Hogg County, Texas",1136.172598,5282,0,2523,...,1,1,0,2,11,988,262,18.8,5.0,4856

,ST,STATE,ST_ABBR,STCNTY,COUNTY,FIPS,LOCATION,AREA_SQMI,E_TOTPOP,M_TOTPOP,...,F_CROWD,F_NOVEH,F_GROUPQ,F_THEME4,F_TOTAL,E_UNINSUR,M_UNINSUR,EP_UNINSUR,MP_UNINSUR,E_DAYPOP
0,1,ALABAMA,AL,1015,Calhoun,1015981901,"Census Tract 9819.01, Calhoun County, Alabama",24.243865,0,12,...,-999,-999,-999,-999,-999,0,12,-999.0,-999.0,656
1,1,ALABAMA,AL,1015,Calhoun,1015981902,"Census Tract 9819.02, Calhoun County, Alabama",34.646714,0,12,...,-999,-999,-999,-999,-999,0,12,-999.0,-999.0,146
2,1,ALABAMA,AL,1015,Calhoun,1015981903,"Census Tract 9819.03, Calhoun County, Alabama",13.926276,0,12,...,-999,-999,-999,-999,-999,0,12,-999.0,-999.0,0
3,1,ALABAMA,AL,1097,Mobile,1097003605,"Census Tract 36.05, Mobile County, Alabama",0.732300,899,316,...,0,-999,1,-999,-999,33,36,3.7,4.1,5135
4,1,ALABAMA,AL,1097,Mobile,1097990000,"Census Tract 9900, Mobile County, Alabama",0.000000,0,12,...,-999,-999,-999,-999,-999,0,12,-999.0,-999.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72832,51,VIRGINIA,VA,51003,Albemarle,51003010903,"Census Tract 109.03, Albemarle County, Virginia",0.378015,3159,553,...,1,1,1,4,6,67,47,2.1,1.3,12094
72833,51,VIRGINIA,VA,51121,Montgomery,51121020202,"Census Tract 202.02, Montgomery County, Virginia",2.278257,2000,232,...,0,1,1,4,7,102,64,6.0,3.6,2222
72834,51,VIRGINIA,VA,51700,Newport News City,51700030100,"Census Tract 301, Newport News city, Virginia",1.636259,4274,612,...,1,1,1,4,9,436,139,14.9,4.6,6558
72835,53,WASHINGTON,WA,53033,King,53033005302,"Census Tract 53.02, King County, Washington",0.968062,5320,629,...,1,1,1,4,7,267,98,5.1,1.8,40043
72836,53,WASHINGTON,WA,53077,Yakima,53077000100,"Census Tract 1, Yakima County, Washington",1.136201,3170,325,...,1,1,1,4,11,450,125,21.8,5.6,18952

### Exploring County

In [15]:
# New Mexico has a random county first, lets reorder it by state then county alphabettically
df_county = df_county.sort_values(["STATE", "COUNTY"])
df_county = df_county.reset_index(drop=True)
df_county

,ST,STATE,ST_ABBR,COUNTY,FIPS,LOCATION,AREA_SQMI,E_TOTPOP,M_TOTPOP,E_HU,...,F_CROWD,F_NOVEH,F_GROUPQ,F_THEME4,F_TOTAL,E_UNINSUR,M_UNINSUR,EP_UNINSUR,MP_UNINSUR,E_DAYPOP
0,1,ALABAMA,AL,Autauga,1001,"Autauga County, Alabama",594.443459,55200,0,23315,...,0,0,0,0,0,3875,508,7.1,0.9,37301
1,1,ALABAMA,AL,Baldwin,1003,"Baldwin County, Alabama",1589.793007,208107,0,111945,...,0,0,0,1,1,20864,1646,10.2,0.8,195677
2,1,ALABAMA,AL,Barbour,1005,"Barbour County, Alabama",885.001636,25782,0,11937,...,0,0,1,2,8,2558,363,11.2,1.6,25052
3,1,ALABAMA,AL,Bibb,1007,"Bibb County, Alabama",622.461089,22527,0,9161,...,0,0,1,2,2,1619,396,7.9,1.9,17696
4,1,ALABAMA,AL,Blount,1009,"Blount County, Alabama",644.830460,57645,0,24222,...,0,0,0,0,0,6303,732,11.0,1.3,40036
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3137,56,WYOMING,WY,Sweetwater,56037,"Sweetwater County, Wyoming",10426.975725,44117,0,19628,...,0,0,0,0,1,5240,794,12.0,1.8,45734
3138,56,WYOMING,WY,Teton,56039,"Teton County, Wyoming",3996.844622,23059,0,13680,...,1,0,0,1,2,2305,603,10.0,2.6,29426
3139,56,WYOMING,WY,Uinta,56041,"Uinta County, Wyoming",2081.719807,20609,0,8972,...,0,0,0,0,1,2499,452,12.2,2.2,19734
3140,56,WYOMING,WY,Washakie,56043,"Washakie County, Wyoming",2238.672972,8129,0,3868,...,0,0,0,0,0,1223,245,15.4,3.1,7859
3141,56,WYOMING,WY,Weston,56045,"Weston County, Wyoming",2398.003891,7100,0,3565,...,0,0,0,0,0,898,215,13.3,3.2,5576